/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface AavePriceOracleInterface extends ethers.utils.Interface {
  functions: {
    "numAssetsPerYieldToken(uint256,uint256)": FunctionFragment;
    "numYieldTokensPerAsset(uint256,uint256)": FunctionFragment;
    "protocolName()": FunctionFragment;
    "storedInterestRate(address)": FunctionFragment;
    "updateInterestRate(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "numAssetsPerYieldToken",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "numYieldTokensPerAsset",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "storedInterestRate",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateInterestRate",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "numAssetsPerYieldToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numYieldTokensPerAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storedInterestRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateInterestRate",
    data: BytesLike
  ): Result;

  events: {};
}

export class AavePriceOracle extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: AavePriceOracleInterface;

  functions: {
    numAssetsPerYieldToken(
      yieldBearingAmount: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    numYieldTokensPerAsset(
      backingTokenAmount: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    protocolName(overrides?: CallOverrides): Promise<[string]>;

    storedInterestRate(
      token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    updateInterestRate(
      token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  numAssetsPerYieldToken(
    yieldBearingAmount: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  numYieldTokensPerAsset(
    backingTokenAmount: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  protocolName(overrides?: CallOverrides): Promise<string>;

  storedInterestRate(
    token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  updateInterestRate(
    token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    numAssetsPerYieldToken(
      yieldBearingAmount: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numYieldTokensPerAsset(
      backingTokenAmount: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    protocolName(overrides?: CallOverrides): Promise<string>;

    storedInterestRate(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateInterestRate(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    numAssetsPerYieldToken(
      yieldBearingAmount: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numYieldTokensPerAsset(
      backingTokenAmount: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    protocolName(overrides?: CallOverrides): Promise<BigNumber>;

    storedInterestRate(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateInterestRate(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    numAssetsPerYieldToken(
      yieldBearingAmount: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    numYieldTokensPerAsset(
      backingTokenAmount: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    protocolName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    storedInterestRate(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateInterestRate(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
