/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface StatisticsInterface extends ethers.utils.Interface {
  functions: {
    "ENS()": FunctionFragment;
    "getRate(bytes32)": FunctionFragment;
    "totalValueLockedAtGivenRate(address,bytes32)": FunctionFragment;
    "totalValueLockedInBackingTokens(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "ENS", values?: undefined): string;
  encodeFunctionData(functionFragment: "getRate", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "totalValueLockedAtGivenRate",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalValueLockedInBackingTokens",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "ENS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalValueLockedAtGivenRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalValueLockedInBackingTokens",
    data: BytesLike
  ): Result;

  events: {};
}

export class Statistics extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: StatisticsInterface;

  functions: {
    ENS(overrides?: CallOverrides): Promise<[string]>;

    getRate(
      chainlinkAggregatorNodeHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { rate: BigNumber; rateDenominator: BigNumber }
    >;

    totalValueLockedAtGivenRate(
      pool: string,
      rateConversionData: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    totalValueLockedInBackingTokens(
      pool: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  ENS(overrides?: CallOverrides): Promise<string>;

  getRate(
    chainlinkAggregatorNodeHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { rate: BigNumber; rateDenominator: BigNumber }
  >;

  totalValueLockedAtGivenRate(
    pool: string,
    rateConversionData: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  totalValueLockedInBackingTokens(
    pool: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    ENS(overrides?: CallOverrides): Promise<string>;

    getRate(
      chainlinkAggregatorNodeHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { rate: BigNumber; rateDenominator: BigNumber }
    >;

    totalValueLockedAtGivenRate(
      pool: string,
      rateConversionData: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalValueLockedInBackingTokens(
      pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    ENS(overrides?: CallOverrides): Promise<BigNumber>;

    getRate(
      chainlinkAggregatorNodeHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalValueLockedAtGivenRate(
      pool: string,
      rateConversionData: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalValueLockedInBackingTokens(
      pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ENS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRate(
      chainlinkAggregatorNodeHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalValueLockedAtGivenRate(
      pool: string,
      rateConversionData: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalValueLockedInBackingTokens(
      pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
