export type Ticker =
  | 'AAVE'
  | 'COMP'
  | 'DAI'
  | 'ETH'
  | 'LIDO'
  | 'Principals' // alias of 'Capital'
  | 'Yields' // alias of 'Yield'
  | 'TLPT'
  | 'TUSD'
  | 'stETH'
  | 'USDC'
  | 'aDAI'
  | 'cDAI'
  | 'LP Token'
  | 'RARI'
  | 'RSPT'
  | 'YEARN'
  | 'FANTOM'
  | 'USDT'
  | 'fUSDT'
  | 'BTC'
  | 'WBTC'
  | 'WETH'
  | 'wFTM'
  | 'YFI'
  | 'yvDAI'
  | 'yvWBTC'
  | 'yvWETH'
  | 'yvYFI'
  | 'yvUSDT'
  | 'yvUSDC';

export type NativeTokenTicker = 'ETH' | 'FTM';

export type PoolShares = 'Principals' | 'Yields';
