const ru = {
  dashboard: 'Щиток приборов',
  analytics: 'Аналитика',
  community: 'Сообщество',
  settings: 'Настройки',
  connectWallet: 'Подключить кошелек',
  pool: 'Pool',
  tvl: 'TVL',
  marketImpliedYield: 'Future APR',
  volume: 'Объем',
  fees: 'Fees',
  term: 'Term',
  startDate: 'Start Date',
  maturity: 'Maturity',
  timeLeft: 'Time Remaining',
  currentPosition: 'Current Position',
  principals: 'Principals',
  yields: 'Yields',
  staked: 'Staked',
  approve: 'Approve',
  execute: 'Execute',
  profitLoss: 'Profit & Loss',
  liquidationValue: 'Liquidation Value',
  from: 'From',
  to: 'To',
};
export default ru;
