type Words =
  | 'dashboard'
  | 'analytics'
  | 'community'
  | 'settings'
  | 'connectWallet'
  | 'tvl'
  | 'pool'
  | 'marketImpliedYield'
  | 'volume'
  | 'fees'
  | 'term'
  | 'startDate'
  | 'maturity'
  | 'timeLeft'
  | 'currentPosition'
  | 'principals'
  | 'yields'
  | 'lpTokens'
  | 'staked'
  | 'approve'
  | 'execute'
  | 'profitLoss'
  | 'liquidationValue'
  | 'from'
  | 'to'
  | 'balance'
  | 'fixYourFutureYield'
  | 'fixedYield'
  | 'fixedYieldAtMaturity'
  | 'totalAvailableAtMaturity'
  | 'provideLiquidity'
  | 'variableYield'
  | 'amountReceived'
  | 'approx';

export default Words;
