type Words =
  | 'dashboard'
  | 'analytics'
  | 'community'
  | 'settings'
  | 'connectWallet'
  | 'tvl'
  | 'pool'
  | 'marketImpliedYield'
  | 'volume'
  | 'fees'
  | 'term'
  | 'startDate'
  | 'maturity'
  | 'timeLeft'
  | 'currentPosition'
  | 'principals'
  | 'yields'
  | 'staked'
  | 'approve'
  | 'execute'
  | 'profitLoss'
  | 'liquidationValue'
  | 'from'
  | 'to';

export default Words;
